/**
 * 初始化 195 个国家基础数据
 * 运行: cd server && node db/seed.js
 */
const db = require('./index')

const countries = [
  { name: '阿富汗', code: 'AF', lat: 33.93, lon: 67.71, landmark: '蓝色清真寺', desc: '马扎里沙里夫的蓝色清真寺，阿富汗最著名的宗教建筑。', cat: '建筑' },
  { name: '阿尔巴尼亚', code: 'AL', lat: 41.33, lon: 19.82, landmark: '培拉特古城', desc: '拥有"千窗之城"美称的世界文化遗产。', cat: '景点' },
  { name: '阿尔及利亚', code: 'DZ', lat: 36.75, lon: 3.04, landmark: '卡斯巴古城', desc: '阿尔及尔的古老城区，世界文化遗产。', cat: '景点' },
  { name: '安道尔', code: 'AD', lat: 42.51, lon: 1.52, landmark: '瓦利拉山谷', desc: '比利牛斯山脉中的美丽山谷。', cat: '景点' },
  { name: '安哥拉', code: 'AO', lat: -8.84, lon: 13.23, landmark: '卡兰杜拉瀑布', desc: '非洲第二大瀑布，壮观的自然景观。', cat: '景点' },
  { name: '安提瓜和巴布达', code: 'AG', lat: 17.06, lon: -61.80, landmark: '纳尔逊船坞', desc: '18世纪英国海军基地遗址，世界文化遗产。', cat: '景点' },
  { name: '阿根廷', code: 'AR', lat: -34.60, lon: -58.38, landmark: '方尖碑', desc: '布宜诺斯艾利斯的标志性纪念碑，纪念城市建立400周年。', cat: '建筑' },
  { name: '亚美尼亚', code: 'AM', lat: 40.18, lon: 44.51, landmark: '埃奇米阿津大教堂', desc: '世界上最古老的大教堂之一。', cat: '建筑' },
  { name: '澳大利亚', code: 'AU', lat: -33.86, lon: 151.21, landmark: '悉尼歌剧院', desc: '澳大利亚地标建筑，以其独特的帆船造型闻名于世。', cat: '建筑' },
  { name: '奥地利', code: 'AT', lat: 48.21, lon: 16.37, landmark: '美泉宫', desc: '维也纳的巴洛克宫殿，哈布斯堡王朝的夏宫。', cat: '建筑' },
  { name: '阿塞拜疆', code: 'AZ', lat: 40.41, lon: 49.87, landmark: '少女塔', desc: '巴库古城中的标志性建筑，世界文化遗产。', cat: '建筑' },
  { name: '巴哈马', code: 'BS', lat: 25.05, lon: -77.35, landmark: '猪岛', desc: '著名的游泳猪沙滩，独特的旅游景点。', cat: '景点' },
  { name: '巴林', code: 'BH', lat: 26.07, lon: 50.56, landmark: '巴林堡', desc: '古老的港口城市遗址，世界文化遗产。', cat: '景点' },
  { name: '孟加拉国', code: 'BD', lat: 23.81, lon: 90.41, landmark: '巴格拉特清真寺', desc: '孟加拉国最大的清真寺之一。', cat: '建筑' },
  { name: '巴巴多斯', code: 'BB', lat: 13.19, lon: -59.54, landmark: '布里奇顿', desc: '历史悠久的首都城区，世界文化遗产。', cat: '景点' },
  { name: '白俄罗斯', code: 'BY', lat: 53.90, lon: 27.57, landmark: '米尔城堡', desc: '16世纪的防御城堡群，世界文化遗产。', cat: '建筑' },
  { name: '比利时', code: 'BE', lat: 50.85, lon: 4.35, landmark: '布鲁塞尔大广场', desc: '欧洲最美广场之一，世界文化遗产。', cat: '景点' },
  { name: '伯利兹', code: 'BZ', lat: 17.19, lon: -88.50, landmark: '蓝洞', desc: '加勒比海中的巨大水下洞穴，潜水圣地。', cat: '景点' },
  { name: '贝宁', code: 'BJ', lat: 6.50, lon: 2.63, landmark: '阿波美王宫', desc: '达荷美王国的皇家宫殿群，世界文化遗产。', cat: '建筑' },
  { name: '不丹', code: 'BT', lat: 27.47, lon: 89.64, landmark: '虎穴寺', desc: '悬崖上的佛教寺庙，不丹最神圣的地方。', cat: '建筑' },
  { name: '玻利维亚', code: 'BO', lat: -16.49, lon: -68.15, landmark: '乌尤尼盐沼', desc: '世界上最大的盐沼，被称为"天空之镜"。', cat: '景点' },
  { name: '波黑', code: 'BA', lat: 43.86, lon: 18.41, landmark: '莫斯塔尔古桥', desc: '16世纪的石拱桥，波黑的标志。', cat: '建筑' },
  { name: '博茨瓦纳', code: 'BW', lat: -19.99, lon: 23.42, landmark: '奥卡万戈三角洲', desc: '世界上最大的内陆三角洲，野生动物天堂。', cat: '景点' },
  { name: '巴西', code: 'BR', lat: -22.95, lon: -43.17, landmark: '基督像', desc: '里约热内卢的标志，矗立在科科瓦多山顶的巨型耶稣基督雕像。', cat: '建筑' },
  { name: '文莱', code: 'BN', lat: 4.93, lon: 114.95, landmark: '奥马尔清真寺', desc: '文莱最大的清真寺，壮观的金色圆顶。', cat: '建筑' },
  { name: '保加利亚', code: 'BG', lat: 42.70, lon: 23.32, landmark: '里拉修道院', desc: '保加利亚最大的修道院，世界文化遗产。', cat: '建筑' },
  { name: '布基纳法索', code: 'BF', lat: 12.37, lon: -1.52, landmark: '洛罗佩尼遗址', desc: '西非最古老的石头建筑群，世界文化遗产。', cat: '景点' },
  { name: '布隆迪', code: 'BI', lat: -3.38, lon: 29.36, landmark: '坦噶尼喀湖', desc: '世界第二深湖，非洲大裂谷的壮观景观。', cat: '景点' },
  { name: '佛得角', code: 'CV', lat: 14.93, lon: -23.51, landmark: '老城', desc: '里贝拉格兰德历史中心，世界文化遗产。', cat: '景点' },
  { name: '柬埔寨', code: 'KH', lat: 13.41, lon: 103.87, landmark: '吴哥窟', desc: '世界上最大的宗教建筑，高棉帝国的辉煌遗产。', cat: '景点' },
  { name: '喀麦隆', code: 'CM', lat: 4.05, lon: 9.69, landmark: '喀麦隆火山', desc: '西非最高峰，壮观的活火山。', cat: '景点' },
  { name: '加拿大', code: 'CA', lat: 43.65, lon: -79.38, landmark: '尼亚加拉瀑布', desc: '世界三大瀑布之一，横跨美加边境的壮观自然奇观。', cat: '景点' },
  { name: '中非', code: 'CF', lat: 4.36, lon: 18.56, landmark: '马诺沃-贡达自然保护区', desc: '中非重要的野生动物保护区。', cat: '景点' },
  { name: '乍得', code: 'TD', lat: 12.11, lon: 15.04, landmark: '恩内迪高原', desc: '撒哈拉沙漠中的岩画遗址。', cat: '景点' },
  { name: '智利', code: 'CL', lat: -27.12, lon: -109.35, landmark: '复活节岛石像', desc: '太平洋上神秘的巨石像，拉帕努伊文明的遗产。', cat: '景点' },
  { name: '中国', code: 'CN', lat: 40.43, lon: 116.57, landmark: '长城', desc: '中国古代伟大的军事防御工程，是世界文化遗产，象征着中华民族的坚韧精神。', cat: '建筑' },
  { name: '哥伦比亚', code: 'CO', lat: 4.71, lon: -74.07, landmark: '卡塔赫纳古城', desc: '加勒比海岸的殖民时代古城，世界文化遗产。', cat: '景点' },
  { name: '科摩罗', code: 'KM', lat: -11.70, lon: 43.26, landmark: '卡尔塔拉火山', desc: '科摩罗群岛的活火山。', cat: '景点' },
  { name: '刚果（布）', code: 'CG', lat: -4.27, lon: 15.28, landmark: '刚果河', desc: '非洲第二长河，世界上最深的河流。', cat: '景点' },
  { name: '刚果（金）', code: 'CD', lat: -4.32, lon: 15.31, landmark: '维龙加国家公园', desc: '非洲最古老的国家公园，山地大猩猩的栖息地。', cat: '景点' },
  { name: '哥斯达黎加', code: 'CR', lat: 9.93, lon: -84.09, landmark: '阿雷纳尔火山', desc: '哥斯达黎加最著名的火山，被热带雨林环绕。', cat: '景点' },
  { name: '科特迪瓦', code: 'CI', lat: 6.83, lon: -5.29, landmark: '和平圣母大教堂', desc: '世界上最大的基督教教堂之一。', cat: '建筑' },
  { name: '克罗地亚', code: 'HR', lat: 42.65, lon: 18.09, landmark: '杜布罗夫尼克古城', desc: '亚得里亚海明珠，《权力的游戏》取景地。', cat: '景点' },
  { name: '古巴', code: 'CU', lat: 23.11, lon: -82.37, landmark: '哈瓦那老城', desc: '充满历史韵味的殖民时代城区，世界文化遗产。', cat: '景点' },
  { name: '塞浦路斯', code: 'CY', lat: 35.17, lon: 33.36, landmark: '帕福斯考古遗址', desc: '古希腊罗马时期的遗迹，世界文化遗产。', cat: '景点' },
  { name: '捷克', code: 'CZ', lat: 50.08, lon: 14.43, landmark: '布拉格城堡', desc: '世界最大的古城堡之一，捷克的象征。', cat: '建筑' },
  { name: '丹麦', code: 'DK', lat: 55.68, lon: 12.59, landmark: '小美人鱼', desc: '哥本哈根港口的铜像，安徒生童话的象征。', cat: '文化符号' },
  { name: '吉布提', code: 'DJ', lat: 11.59, lon: 43.15, landmark: '阿萨尔湖', desc: '非洲大陆最低点，世界上含盐量最高的湖泊之一。', cat: '景点' },
  { name: '多米尼克', code: 'DM', lat: 15.30, lon: -61.39, landmark: '沸腾湖', desc: '世界第二大热泉湖。', cat: '景点' },
  { name: '多米尼加', code: 'DO', lat: 18.47, lon: -69.90, landmark: '圣多明各殖民城', desc: '美洲最古老的欧洲殖民城市，世界文化遗产。', cat: '景点' },
  { name: '厄瓜多尔', code: 'EC', lat: -0.18, lon: -78.47, landmark: '加拉帕戈斯群岛', desc: '达尔文进化论的灵感来源，独特的生态系统。', cat: '景点' },
  { name: '埃及', code: 'EG', lat: 29.98, lon: 31.13, landmark: '金字塔', desc: '古埃及法老的陵墓，是世界七大奇迹之一。', cat: '建筑' },
  { name: '萨尔瓦多', code: 'SV', lat: 13.69, lon: -89.19, landmark: '霍亚德塞伦', desc: '被火山灰保存的玛雅村庄遗址。', cat: '景点' },
  { name: '赤道几内亚', code: 'GQ', lat: 3.75, lon: 8.78, landmark: '比奥科岛', desc: '大西洋上的火山岛，生物多样性丰富。', cat: '景点' },
  { name: '厄立特里亚', code: 'ER', lat: 15.34, lon: 38.93, landmark: '阿斯马拉', desc: '非洲现代主义建筑之都，世界文化遗产。', cat: '建筑' },
  { name: '爱沙尼亚', code: 'EE', lat: 59.44, lon: 24.75, landmark: '塔林老城', desc: '保存完好的中世纪城区，世界文化遗产。', cat: '景点' },
  { name: '斯威士兰', code: 'SZ', lat: -26.52, lon: 31.47, landmark: '希波石', desc: '斯威士兰最大的花岗岩巨石。', cat: '景点' },
  { name: '埃塞俄比亚', code: 'ET', lat: 12.03, lon: 39.04, landmark: '拉利贝拉岩石教堂', desc: '从岩石中开凿的教堂群，被称为"非洲的耶路撒冷"。', cat: '建筑' },
  { name: '斐济', code: 'FJ', lat: -17.78, lon: 177.96, landmark: '玛玛努卡群岛', desc: '南太平洋的热带天堂群岛。', cat: '景点' },
  { name: '芬兰', code: 'FI', lat: 60.17, lon: 24.94, landmark: '圣诞老人村', desc: '位于罗瓦涅米的圣诞主题景点。', cat: '景点' },
  { name: '法国', code: 'FR', lat: 48.86, lon: 2.29, landmark: '埃菲尔铁塔', desc: '巴黎的标志性建筑，建于1889年，是法国最著名的地标之一。', cat: '建筑' },
  { name: '加蓬', code: 'GA', lat: 0.39, lon: 9.45, landmark: '洛佩国家公园', desc: '热带雨林与草原交汇处，世界自然遗产。', cat: '景点' },
  { name: '冈比亚', code: 'GM', lat: 13.45, lon: -16.58, landmark: '詹姆斯岛', desc: '大西洋奴隶贸易的历史遗址，世界文化遗产。', cat: '景点' },
  { name: '格鲁吉亚', code: 'GE', lat: 41.69, lon: 44.80, landmark: '梅斯蒂亚', desc: '高加索山脉中的中世纪防御塔群。', cat: '建筑' },
  { name: '德国', code: 'DE', lat: 52.52, lon: 13.41, landmark: '勃兰登堡门', desc: '柏林的标志性建筑，是德国统一与和平的象征。', cat: '建筑' },
  { name: '加纳', code: 'GH', lat: 5.60, lon: -0.19, landmark: '阿克拉独立广场', desc: '加纳独立运动的象征性广场。', cat: '景点' },
  { name: '希腊', code: 'GR', lat: 37.97, lon: 23.73, landmark: '帕特农神庙', desc: '雅典卫城的古希腊神庙，是西方文明的象征。', cat: '建筑' },
  { name: '格林纳达', code: 'GD', lat: 12.06, lon: -61.75, landmark: '大安斯海滩', desc: '加勒比海著名的白沙滩。', cat: '景点' },
  { name: '危地马拉', code: 'GT', lat: 17.22, lon: -89.62, landmark: '蒂卡尔', desc: '玛雅文明最大的城市遗址之一。', cat: '景点' },
  { name: '几内亚', code: 'GN', lat: 9.95, lon: -11.79, landmark: '宁巴山', desc: '西非最高峰之一，世界自然遗产。', cat: '景点' },
  { name: '几内亚比绍', code: 'GW', lat: 11.86, lon: -15.60, landmark: '比热戈斯群岛', desc: '大西洋上的生物圈保护区。', cat: '景点' },
  { name: '圭亚那', code: 'GY', lat: 5.85, lon: -58.93, landmark: '凯厄图尔瀑布', desc: '世界上最大的单级落差瀑布之一。', cat: '景点' },
  { name: '海地', code: 'HT', lat: 19.76, lon: -72.34, landmark: '拉费里耶尔城堡', desc: '西半球最大的城堡，世界文化遗产。', cat: '建筑' },
  { name: '洪都拉斯', code: 'HN', lat: 14.84, lon: -89.14, landmark: '科潘遗址', desc: '玛雅文明的重要城市遗址。', cat: '景点' },
  { name: '匈牙利', code: 'HU', lat: 47.50, lon: 19.04, landmark: '布达佩斯城堡', desc: '多瑙河畔的壮观城堡群，世界文化遗产。', cat: '建筑' },
  { name: '冰岛', code: 'IS', lat: 64.15, lon: -21.94, landmark: '蓝湖温泉', desc: '冰岛最著名的地热温泉。', cat: '景点' },
  { name: '印度', code: 'IN', lat: 27.17, lon: 78.04, landmark: '泰姬陵', desc: '印度最著名的建筑，是莫卧儿帝国时期的杰作，象征着永恒的爱情。', cat: '建筑' },
  { name: '印度尼西亚', code: 'ID', lat: -7.61, lon: 110.20, landmark: '婆罗浮屠', desc: '世界上最大的佛教寺庙，爪哇岛上的古代奇迹。', cat: '景点' },
  { name: '伊朗', code: 'IR', lat: 32.66, lon: 51.68, landmark: '伊玛目广场', desc: '伊斯法罕的历史广场，波斯建筑艺术的杰出代表。', cat: '景点' },
  { name: '伊拉克', code: 'IQ', lat: 33.31, lon: 44.37, landmark: '巴比伦遗址', desc: '古巴比伦文明的发祥地。', cat: '景点' },
  { name: '爱尔兰', code: 'IE', lat: 53.35, lon: -6.26, landmark: '莫赫悬崖', desc: '爱尔兰西海岸的壮观悬崖景观。', cat: '景点' },
  { name: '以色列', code: 'IL', lat: 31.78, lon: 35.24, landmark: '耶路撒冷老城', desc: '三大宗教的圣城，世界文化遗产。', cat: '景点' },
  { name: '意大利', code: 'IT', lat: 41.90, lon: 12.50, landmark: '罗马斗兽场', desc: '古罗马时期最大的圆形竞技场，是罗马帝国的象征。', cat: '景点' },
  { name: '牙买加', code: 'JM', lat: 18.11, lon: -77.30, landmark: '蓝山', desc: '著名的蓝山咖啡产地，壮观的山脉景观。', cat: '景点' },
  { name: '日本', code: 'JP', lat: 35.68, lon: 139.69, landmark: '富士山', desc: '日本最高峰，被视为日本精神与文化的象征。', cat: '景点' },
  { name: '约旦', code: 'JO', lat: 30.33, lon: 35.44, landmark: '佩特拉古城', desc: '纳巴泰人在岩石中雕凿的古城，被称为"玫瑰之城"。', cat: '景点' },
  { name: '哈萨克斯坦', code: 'KZ', lat: 51.13, lon: 71.43, landmark: '巴伊杰列克塔', desc: '阿斯塔纳的标志性建筑，象征哈萨克民间传说。', cat: '建筑' },
  { name: '肯尼亚', code: 'KE', lat: -1.29, lon: 36.82, landmark: '马赛马拉', desc: '世界著名的野生动物保护区，每年上演壮观的动物大迁徙。', cat: '景点' },
  { name: '基里巴斯', code: 'KI', lat: 1.87, lon: -157.36, landmark: '圣诞岛', desc: '世界上最大的珊瑚环礁。', cat: '景点' },
  { name: '朝鲜', code: 'KP', lat: 39.03, lon: 125.75, landmark: '主体思想塔', desc: '平壤的标志性建筑。', cat: '建筑' },
  { name: '韩国', code: 'KR', lat: 37.57, lon: 126.98, landmark: '景福宫', desc: '首尔最大的古代宫殿，朝鲜王朝的正宫。', cat: '建筑' },
  { name: '科威特', code: 'KW', lat: 29.38, lon: 47.99, landmark: '科威特塔', desc: '科威特城的标志性建筑群。', cat: '建筑' },
  { name: '吉尔吉斯斯坦', code: 'KG', lat: 42.87, lon: 74.59, landmark: '伊塞克湖', desc: '中亚最大的湖泊，被雪山环绕。', cat: '景点' },
  { name: '老挝', code: 'LA', lat: 19.89, lon: 102.14, landmark: '琅勃拉邦', desc: '湄公河畔的古都，世界文化遗产。', cat: '景点' },
  { name: '拉脱维亚', code: 'LV', lat: 56.95, lon: 24.11, landmark: '里加老城', desc: '波罗的海最大城市的历史中心，世界文化遗产。', cat: '景点' },
  { name: '黎巴嫩', code: 'LB', lat: 34.01, lon: 35.65, landmark: '巴勒贝克', desc: '古罗马时期最壮观的神庙遗址之一。', cat: '景点' },
  { name: '莱索托', code: 'LS', lat: -29.31, lon: 28.48, landmark: '马莱苏尼亚尼瀑布', desc: '非洲南部最高的瀑布之一。', cat: '景点' },
  { name: '利比里亚', code: 'LR', lat: 6.43, lon: -10.40, landmark: '萨波国家公园', desc: '西非最大的热带雨林保护区之一。', cat: '景点' },
  { name: '利比亚', code: 'LY', lat: 32.90, lon: 13.18, landmark: '莱普提斯', desc: '保存最完好的古罗马城市遗址之一。', cat: '景点' },
  { name: '列支敦士登', code: 'LI', lat: 47.14, lon: 9.52, landmark: '瓦杜兹城堡', desc: '列支敦士登王室的官方住所。', cat: '建筑' },
  { name: '立陶宛', code: 'LT', lat: 54.69, lon: 25.28, landmark: '维尔纽斯老城', desc: '东欧最大的巴洛克风格老城，世界文化遗产。', cat: '景点' },
  { name: '卢森堡', code: 'LU', lat: 49.61, lon: 6.13, landmark: '卢森堡古堡', desc: '建在悬崖上的城堡要塞，世界文化遗产。', cat: '建筑' },
  { name: '马达加斯加', code: 'MG', lat: -18.91, lon: 47.52, landmark: '猴面包树大道', desc: '马达加斯加标志性的自然景观。', cat: '景点' },
  { name: '马拉维', code: 'MW', lat: -13.97, lon: 33.79, landmark: '马拉维湖', desc: '非洲第三大湖，拥有独特的淡水鱼种群。', cat: '景点' },
  { name: '马来西亚', code: 'MY', lat: 3.14, lon: 101.69, landmark: '双子塔', desc: '吉隆坡的标志性建筑，世界最高的双子塔。', cat: '建筑' },
  { name: '马尔代夫', code: 'MV', lat: 4.18, lon: 73.51, landmark: '马累环礁', desc: '印度洋上的热带天堂群岛。', cat: '景点' },
  { name: '马里', code: 'ML', lat: 14.00, lon: -5.00, landmark: '杰内大清真寺', desc: '世界上最大的泥砖建筑，世界文化遗产。', cat: '建筑' },
  { name: '马耳他', code: 'MT', lat: 35.90, lon: 14.51, landmark: '瓦莱塔', desc: '地中海岛国的历史首都，世界文化遗产。', cat: '景点' },
  { name: '马绍尔群岛', code: 'MH', lat: 7.12, lon: 171.18, landmark: '比基尼环礁', desc: '历史性的核试验场地，世界文化遗产。', cat: '景点' },
  { name: '毛里塔尼亚', code: 'MR', lat: 18.09, lon: -15.98, landmark: '欣盖提', desc: '撒哈拉沙漠中的古老绿洲城市。', cat: '景点' },
  { name: '毛里求斯', code: 'MU', lat: -20.16, lon: 57.50, landmark: '七色土', desc: '独特的彩色地质奇观。', cat: '景点' },
  { name: '墨西哥', code: 'MX', lat: 20.68, lon: -88.57, landmark: '奇琴伊察', desc: '玛雅文明的重要遗址，以库库尔坎金字塔闻名。', cat: '景点' },
  { name: '密克罗尼西亚', code: 'FM', lat: 6.92, lon: 158.16, landmark: '南马都尔', desc: '太平洋上的古代石头城市遗址。', cat: '景点' },
  { name: '摩尔多瓦', code: 'MD', lat: 47.01, lon: 28.86, landmark: '米列什蒂米茨酒窖', desc: '世界上最大的葡萄酒收藏。', cat: '文化符号' },
  { name: '摩纳哥', code: 'MC', lat: 43.74, lon: 7.43, landmark: '蒙特卡洛赌场', desc: '世界上最著名的赌场之一。', cat: '建筑' },
  { name: '蒙古', code: 'MN', lat: 47.92, lon: 106.92, landmark: '成吉思汗骑马像', desc: '世界上最大的骑马雕像。', cat: '建筑' },
  { name: '黑山', code: 'ME', lat: 42.44, lon: 18.77, landmark: '科托尔古城', desc: '亚得里亚海畔的中世纪城镇，世界文化遗产。', cat: '景点' },
  { name: '摩洛哥', code: 'MA', lat: 33.97, lon: -6.85, landmark: '哈桑二世清真寺', desc: '卡萨布兰卡的地标建筑，世界第三大清真寺。', cat: '建筑' },
  { name: '莫桑比克', code: 'MZ', lat: -15.12, lon: 39.27, landmark: '莫桑比克岛', desc: '葡萄牙殖民时代的历史岛屿，世界文化遗产。', cat: '景点' },
  { name: '缅甸', code: 'MM', lat: 21.17, lon: 94.86, landmark: '蒲甘', desc: '缅甸最壮观的佛塔群，数千座古塔遍布平原。', cat: '景点' },
  { name: '纳米比亚', code: 'NA', lat: -24.65, lon: 15.96, landmark: '死亡谷', desc: '纳米布沙漠中超现实的枯树景观。', cat: '景点' },
  { name: '瑙鲁', code: 'NR', lat: -0.52, lon: 166.93, landmark: '安尼巴雷区', desc: '太平洋上最小国家的海岸景观。', cat: '景点' },
  { name: '尼泊尔', code: 'NP', lat: 27.99, lon: 86.93, landmark: '珠穆朗玛峰', desc: '世界最高峰，海拔8848.86米，位于中尼边境。', cat: '景点' },
  { name: '荷兰', code: 'NL', lat: 52.37, lon: 4.90, landmark: '风车村', desc: '荷兰标志性的风车景观，记录着与水斗争的历史。', cat: '文化符号' },
  { name: '新西兰', code: 'NZ', lat: -44.67, lon: 167.93, landmark: '米尔福德峡湾', desc: '新西兰最著名的峡湾，被誉为"世界第八大奇迹"。', cat: '景点' },
  { name: '尼加拉瓜', code: 'NI', lat: 12.11, lon: -86.27, landmark: '莱昂大教堂', desc: '中美洲最大的大教堂，世界文化遗产。', cat: '建筑' },
  { name: '尼日尔', code: 'NE', lat: 17.61, lon: 8.08, landmark: '阿伊尔高原', desc: '撒哈拉沙漠中的山脉与绿洲。', cat: '景点' },
  { name: '尼日利亚', code: 'NG', lat: 9.06, lon: 7.49, landmark: '祖马岩', desc: '阿布贾的标志性巨石。', cat: '景点' },
  { name: '北马其顿', code: 'MK', lat: 41.00, lon: 20.94, landmark: '奥赫里德湖', desc: '欧洲最古老的湖泊之一，世界自然与文化遗产。', cat: '景点' },
  { name: '挪威', code: 'NO', lat: 60.47, lon: 6.73, landmark: '峡湾', desc: '挪威最壮观的自然景观，冰川侵蚀形成的狭长海湾。', cat: '景点' },
  { name: '阿曼', code: 'OM', lat: 23.59, lon: 58.55, landmark: '苏丹卡布斯大清真寺', desc: '阿曼最大的清真寺，壮观的伊斯兰建筑。', cat: '建筑' },
  { name: '巴基斯坦', code: 'PK', lat: 33.73, lon: 73.09, landmark: '巴德夏希清真寺', desc: '拉合尔的莫卧儿帝国清真寺。', cat: '建筑' },
  { name: '帕劳', code: 'PW', lat: 7.51, lon: 134.58, landmark: '水母湖', desc: '世界上独一无二的无毒水母湖。', cat: '景点' },
  { name: '巴拿马', code: 'PA', lat: 9.10, lon: -79.52, landmark: '巴拿马运河', desc: '连接大西洋与太平洋的伟大工程。', cat: '景点' },
  { name: '巴布亚新几内亚', code: 'PG', lat: -6.31, lon: 143.96, landmark: '库克早期农业遗址', desc: '世界上最早的农业发源地之一。', cat: '景点' },
  { name: '巴拉圭', code: 'PY', lat: -25.26, lon: -57.58, landmark: '耶稣和特立尼达耶稣会传教区', desc: '南美洲保存最好的耶稣会传教区遗址。', cat: '景点' },
  { name: '秘鲁', code: 'PE', lat: -13.16, lon: -72.55, landmark: '马丘比丘', desc: '印加帝国的古城遗址，被称为"天空之城"。', cat: '景点' },
  { name: '菲律宾', code: 'PH', lat: 10.31, lon: 123.89, landmark: '巧克力山', desc: '薄荷岛上独特的圆锥形山丘群。', cat: '景点' },
  { name: '波兰', code: 'PL', lat: 50.05, lon: 19.94, landmark: '维利奇卡盐矿', desc: '世界上最古老的盐矿之一，地下教堂令人叹为观止。', cat: '景点' },
  { name: '葡萄牙', code: 'PT', lat: 38.69, lon: -9.22, landmark: '贝伦塔', desc: '里斯本的防御塔楼，大航海时代的象征。', cat: '建筑' },
  { name: '卡塔尔', code: 'QA', lat: 25.29, lon: 51.53, landmark: '伊斯兰艺术博物馆', desc: '多哈的标志性建筑，收藏伊斯兰艺术精品。', cat: '建筑' },
  { name: '罗马尼亚', code: 'RO', lat: 45.66, lon: 25.20, landmark: '布朗城堡', desc: '特兰西瓦尼亚的"吸血鬼城堡"。', cat: '建筑' },
  { name: '俄罗斯', code: 'RU', lat: 55.75, lon: 37.62, landmark: '克里姆林宫', desc: '莫斯科的心脏，俄罗斯联邦的政治中心和世界文化遗产。', cat: '建筑' },
  { name: '卢旺达', code: 'RW', lat: -1.94, lon: 29.87, landmark: '火山国家公园', desc: '山地大猩猩的家园，非洲最珍贵的自然保护区。', cat: '景点' },
  { name: '圣基茨和尼维斯', code: 'KN', lat: 17.36, lon: -62.78, landmark: '硫磺石山堡', desc: '加勒比海的军事堡垒，世界文化遗产。', cat: '建筑' },
  { name: '圣卢西亚', code: 'LC', lat: 13.91, lon: -61.00, landmark: '双峰山', desc: '加勒比海的标志性火山双峰。', cat: '景点' },
  { name: '圣文森特和格林纳丁斯', code: 'VC', lat: 13.16, lon: -61.23, landmark: '苏弗里耶尔火山', desc: '圣文森特岛的活火山。', cat: '景点' },
  { name: '萨摩亚', code: 'WS', lat: -13.83, lon: -172.00, landmark: '苏阿海沟', desc: '天然的火山岩游泳洞。', cat: '景点' },
  { name: '圣马力诺', code: 'SM', lat: 43.94, lon: 12.45, landmark: '瓜伊塔塔', desc: '圣马力诺三座城堡中最古老的一座。', cat: '建筑' },
  { name: '圣多美和普林西比', code: 'ST', lat: 0.34, lon: 6.73, landmark: '大狗峰', desc: '火山岩柱，圣多美岛的标志。', cat: '景点' },
  { name: '沙特阿拉伯', code: 'SA', lat: 24.63, lon: 46.72, landmark: '麦加大清真寺', desc: '伊斯兰教最神圣的地方。', cat: '建筑' },
  { name: '塞内加尔', code: 'SN', lat: 14.69, lon: -17.45, landmark: '戈雷岛', desc: '大西洋奴隶贸易的见证，世界文化遗产。', cat: '景点' },
  { name: '塞尔维亚', code: 'RS', lat: 44.82, lon: 20.46, landmark: '贝尔格莱德要塞', desc: '多瑙河与萨瓦河交汇处的古老城堡。', cat: '建筑' },
  { name: '塞舌尔', code: 'SC', lat: -4.68, lon: 55.49, landmark: '五月谷', desc: '世界自然遗产，海椰子的故乡。', cat: '景点' },
  { name: '塞拉利昂', code: 'SL', lat: 8.48, lon: -13.23, landmark: '棉花树', desc: '弗里敦的标志性古树。', cat: '文化符号' },
  { name: '新加坡', code: 'SG', lat: 1.35, lon: 103.82, landmark: '滨海湾花园', desc: '未来主义的超级树林和穹顶花园。', cat: '景点' },
  { name: '斯洛伐克', code: 'SK', lat: 48.15, lon: 17.11, landmark: '斯皮什城堡', desc: '中欧最大的城堡遗址之一，世界文化遗产。', cat: '建筑' },
  { name: '斯洛文尼亚', code: 'SI', lat: 46.37, lon: 14.11, landmark: '布莱德湖', desc: '阿尔卑斯山中的翡翠色湖泊，湖中有小岛教堂。', cat: '景点' },
  { name: '所罗门群岛', code: 'SB', lat: -9.43, lon: 160.02, landmark: '瓜达尔卡纳尔岛', desc: '二战太平洋战场的重要历史遗址。', cat: '景点' },
  { name: '索马里', code: 'SO', lat: 2.05, lon: 45.32, landmark: '拉斯格雷尔岩画', desc: '非洲之角最重要的史前岩画群。', cat: '景点' },
  { name: '南非', code: 'ZA', lat: -33.92, lon: 18.42, landmark: '桌山', desc: '开普敦的标志性山脉，以其平坦的山顶闻名于世。', cat: '景点' },
  { name: '南苏丹', code: 'SS', lat: 4.85, lon: 31.58, landmark: '苏德沼泽', desc: '世界上最大的湿地之一。', cat: '景点' },
  { name: '西班牙', code: 'ES', lat: 41.39, lon: 2.17, landmark: '圣家族大教堂', desc: '高迪设计的巴塞罗那教堂，是加泰罗尼亚现代主义建筑的杰作。', cat: '建筑' },
  { name: '斯里兰卡', code: 'LK', lat: 7.95, lon: 80.76, landmark: '狮子岩', desc: '巨石上的古代宫殿遗址，被称为"世界第八大奇迹"。', cat: '景点' },
  { name: '苏丹', code: 'SD', lat: 16.92, lon: 33.82, landmark: '麦罗埃金字塔', desc: '努比亚文明的金字塔群。', cat: '景点' },
  { name: '苏里南', code: 'SR', lat: 5.82, lon: -55.17, landmark: '帕拉马里博内城', desc: '荷兰殖民时代的历史城区，世界文化遗产。', cat: '景点' },
  { name: '瑞典', code: 'SE', lat: 59.33, lon: 18.07, landmark: '瓦萨号博物馆', desc: '斯德哥尔摩的独特博物馆，展示17世纪沉船。', cat: '文化符号' },
  { name: '瑞士', code: 'CH', lat: 46.95, lon: 7.45, landmark: '马特洪峰', desc: '阿尔卑斯山最著名的山峰，以其锥形山顶闻名。', cat: '景点' },
  { name: '叙利亚', code: 'SY', lat: 33.51, lon: 36.29, landmark: '帕尔米拉', desc: '古代丝绸之路上的沙漠绿洲城市遗址。', cat: '景点' },
  { name: '塔吉克斯坦', code: 'TJ', lat: 38.56, lon: 68.77, landmark: '伊斯莫尔·索莫尼峰', desc: '中亚最高峰。', cat: '景点' },
  { name: '坦桑尼亚', code: 'TZ', lat: -3.07, lon: 37.35, landmark: '乞力马扎罗山', desc: '非洲最高峰，著名的赤道雪山。', cat: '景点' },
  { name: '泰国', code: 'TH', lat: 13.75, lon: 100.49, landmark: '大皇宫', desc: '曼谷最著名的建筑群，泰国王室的象征。', cat: '建筑' },
  { name: '东帝汶', code: 'TL', lat: -8.56, lon: 125.57, landmark: '基督像', desc: '帝力的基督国王雕像。', cat: '建筑' },
  { name: '多哥', code: 'TG', lat: 6.14, lon: 1.21, landmark: '库塔马库', desc: '泥塔建筑群，世界文化遗产。', cat: '建筑' },
  { name: '汤加', code: 'TO', lat: -21.21, lon: -175.20, landmark: '哈阿蒙加三石门', desc: '太平洋上的巨石建筑遗址。', cat: '景点' },
  { name: '特立尼达和多巴哥', code: 'TT', lat: 10.69, lon: -61.22, landmark: '沥青湖', desc: '世界上最大的天然沥青湖。', cat: '景点' },
  { name: '突尼斯', code: 'TN', lat: 36.81, lon: 10.18, landmark: '迦太基遗址', desc: '古罗马与腓尼基文明的交汇点。', cat: '景点' },
  { name: '土耳其', code: 'TR', lat: 41.01, lon: 28.98, landmark: '圣索菲亚大教堂', desc: '伊斯坦布尔的历史建筑，曾为教堂、清真寺，现为博物馆。', cat: '建筑' },
  { name: '土库曼斯坦', code: 'TM', lat: 40.25, lon: 58.44, landmark: '地狱之门', desc: '达瓦札天然气坑，燃烧至今的地下火焰。', cat: '景点' },
  { name: '图瓦卢', code: 'TV', lat: -8.52, lon: 179.20, landmark: '富纳富提环礁', desc: '太平洋上极危的珊瑚环礁岛国。', cat: '景点' },
  { name: '乌干达', code: 'UG', lat: 0.35, lon: 32.62, landmark: '布温迪国家公园', desc: '山地大猩猩的栖息地，世界自然遗产。', cat: '景点' },
  { name: '乌克兰', code: 'UA', lat: 50.45, lon: 30.52, landmark: '圣索菲亚大教堂', desc: '基辅的千年大教堂，世界文化遗产。', cat: '建筑' },
  { name: '阿联酋', code: 'AE', lat: 25.20, lon: 55.27, landmark: '哈利法塔', desc: '迪拜的超级摩天大楼，世界上最高的建筑。', cat: '建筑' },
  { name: '英国', code: 'GB', lat: 51.51, lon: -0.13, landmark: '大本钟', desc: '伦敦著名的钟楼，是英国文化的标志性符号。', cat: '建筑' },
  { name: '美国', code: 'US', lat: 40.69, lon: -74.04, landmark: '自由女神像', desc: '位于纽约港的巨型雕像，是美国自由与民主的象征。', cat: '建筑' },
  { name: '乌拉圭', code: 'UY', lat: -34.91, lon: -56.16, landmark: '科洛尼亚历史城区', desc: '乌拉圭最古老的城镇，世界文化遗产。', cat: '景点' },
  { name: '乌兹别克斯坦', code: 'UZ', lat: 41.30, lon: 69.28, landmark: '撒马尔罕', desc: '丝绸之路上的古城，帖木儿帝国的首都。', cat: '景点' },
  { name: '瓦努阿图', code: 'VU', lat: -17.73, lon: 168.32, landmark: '亚苏尔火山', desc: '世界上最容易接近的活火山之一。', cat: '景点' },
  { name: '梵蒂冈', code: 'VA', lat: 41.90, lon: 12.45, landmark: '圣彼得大教堂', desc: '世界上最大的教堂，天主教的中心。', cat: '建筑' },
  { name: '委内瑞拉', code: 'VE', lat: 5.96, lon: -62.54, landmark: '天使瀑布', desc: '世界上落差最大的瀑布。', cat: '景点' },
  { name: '越南', code: 'VN', lat: 20.96, lon: 107.05, landmark: '下龙湾', desc: '越南最著名的自然景观，石灰岩岛屿星罗棋布的海上仙境。', cat: '景点' },
  { name: '也门', code: 'YE', lat: 15.55, lon: 48.52, landmark: '希巴姆古城', desc: '被称为"沙漠中的曼哈顿"的泥砖高楼群。', cat: '建筑' },
  { name: '赞比亚', code: 'ZM', lat: -17.92, lon: 25.86, landmark: '维多利亚瀑布', desc: '世界上最大的瀑布之一，赞比亚与津巴布韦的界标。', cat: '景点' },
  { name: '津巴布韦', code: 'ZW', lat: -20.27, lon: 30.93, landmark: '大津巴布韦遗址', desc: '非洲南部最大的古代石头建筑遗址。', cat: '景点' },
]

// 开启事务批量插入
const insert = db.prepare(`
  INSERT OR IGNORE INTO landmarks (country_name, country_code, latitude, longitude, landmark_name, description, icon_url, image_url, category)
  VALUES (@country_name, @country_code, @latitude, @longitude, @landmark_name, @description, '', '', @category)
`)

const insertMany = db.transaction((items) => {
  for (const c of items) {
    insert.run({
      country_name: c.name,
      country_code: c.code,
      latitude: c.lat,
      longitude: c.lon,
      landmark_name: c.landmark,
      description: c.desc,
      category: c.cat
    })
  }
})

// 先清空再插入
db.prepare('DELETE FROM landmarks').run()
insertMany(countries)

const count = db.prepare('SELECT COUNT(*) as total FROM landmarks').get()
console.log(`✅ 成功插入 ${count.total} 个国家地标数据`)
process.exit(0)
